#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created Wed Feb 16 10:42:07 2022

@author: (kinkan)
"""

from psaw import PushshiftAPI
import datetime
import pandas as pd
import nltk
import seaborn as sns
sns.set(style='darkgrid', context='talk', palette='Dark2')



from nltk.sentiment.vader import SentimentIntensityAnalyzer as SIA
nltk.download('vader_lexicon')

api = PushshiftAPI()

start_time = int(datetime.datetime(2021,1,5).timestamp())

end_time = int(datetime.datetime(2021,1,8).timestamp())

submissions = api.search_submissions(after=start_time,
                                     before=end_time,
                                     subreddit='wallstreetbets')#,
                                     #filter=['url','author','title','subreddit'])


posts = []


sia = SIA()


headline = set()

results = []


for submission in submissions:
    
    words = submission.title.split()
    cashtags = list(set(filter(lambda word: word.lower().startswith('$'), words)))
       
    if len(cashtags) > 0:
           
        headline.add(submission.title)
            
        UTC_d = submission.created_utc
        d = datetime.datetime.fromtimestamp(UTC_d)
        
    if submission.num_comments > 10:
            
        for line in headline:
                
            pol_score = sia.polarity_scores(line)
                
            pol_score['title'] = line
            pol_score['# comments'] = submission.num_comments
            pol_score['date'] = d
            pol_score['Cashtag'] = cashtags
            
       
     
            results.append(pol_score)
                

df = pd.DataFrame.from_records(results)
df.head()

df['label'] = 0
df.loc[df['compound'] > 0.2, 'label'] = 1
df.loc[df['compound'] < -0.2, 'label'] = -1
df.head()

df2 = df[['Cashtag','title','label', '# comments', 'date']]

df2.to_csv('datatest1.csv', mode='a', encoding='utf-8', index=False)





